# Generated by Django 5.2.7 on 2025-11-02 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apply_Model',
            new_name='Apply',
        ),
        migrations.RenameModel(
            old_name='Contact_Model',
            new_name='Contact',
        ),
    ]
