# Generated by Django 5.2.7 on 2025-11-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_websiteuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_qualification', models.CharField(max_length=100)),
                ('percentage_year', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('course_interest', models.CharField(max_length=150)),
                ('english_test', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
