# Generated by Django 6.0 on 2025-12-22 08:02

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postblog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tital', models.CharField(max_length=150)),
                ('contant', models.TextField(max_length=300)),
                ('slug', autoslug.fields.AutoSlugField(default=0, editable=False, null=True, populate_from='Tital', unique=True)),
            ],
        ),
    ]
